# Generated by Django 6.1 on 2026-08-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('WON', 'Выигран'), ('LOST', 'Проигран')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'db_table': 'tenders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('WON', 'Выигран'), ('LOST', 'Проигран')], max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('WON', 'Выигран'), ('LOST', 'Проигран')], max_length=20, verbose_name='Новый статус')),
                ('changed_by', models.CharField(max_length=255, verbose_name='Кем изменён')),
                ('reason', models.TextField(verbose_name='Причина изменения')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменён')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tenders.tender', verbose_name='Тендер')),
            ],
            options={
                'verbose_name': 'История статуса тендера',
                'verbose_name_plural': 'История статусов тендеров',
                'db_table': 'tender_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
